### ISSUE TITLE
Non symmetric logo

### ISSUE THREAD

**Issue by Aster89** [bitwizeshift/BackportCpp#22]
Call me picky, but the arrow of the logo is not symmetric :P

Very nice project, however :D

**Comment by bitwizeshift** [comment]
Hey @Aster89 -- thanks for reporting this! 

Unfortunately this issue has not been a priority since it's not code-related, so I never really got around to it. However, @catskul provided a great fix to address this! 😄

**Comment by Aster89** [comment]
Wow, great :+1:
